### ISSUE TITLE
jQuery string sometimes appended to today's matches JSON

### ISSUE THREAD

**Issue by arghgr** [estiens/world_cup_json#94] opened 2018-06-18 17:00 UTC
Hi, there's a jQuery string wrapped around matches/today that sometimes shows up every couple of requests, and it's breaking my JSON parser.

For some reason it's not showing up when I put the below code in Markdown code quotes, but here's an example of what it looks like in http://worldcup.sfg.io/matches/today:

jQuery112406228161649446853_1529323514566(
[
{
venue: "Nizhny Novgorod",
location: "Nizhny Novgorod Stadium",
status: "completed",
time: "full-time",
fifa_id: "300331499",
_...etc._
}
]
)

**Comment by estiens** [comment] 2018-06-18 17:48
hmmmm, i've never seen that, but let me check the logs. Are you using JSONP and sending in a callback parameter or just requesting normally?

**Comment by arghgr** [comment] 2018-06-18 17:57
Thanks for responding. Not using JSONP, requesting with this header:
```
request({
  url: "http://worldcup.sfg.io/matches/today",
  headers: {
    "User-Agent": "worldcupgolbot by @arghgr"
  }
}, function(error, response, data) { _...etc._ }
);

```

**Comment by estiens** [comment] 2018-06-18 18:07
Can you try setting 
`Content-Type: application/json`
in your headers?

I'm not sure why it would be /occasionally/ wrapping with that weird jQuery call, and you shouldn't have to send that header, but see if sending it reduces/eliminates the occasional weird response?

**Comment by arghgr** [comment] 2018-06-18 18:23
Just added it, no dice-- it still occasionally fails with a jQuery string. But the frequency of failure has gone down from every two or three requests to every five or so.

**Comment by estiens** [comment] 2018-06-18 18:30
ok, I'll keep looking into it and see if I can reproduce or if anyone else chimes in with the same problem or a solution. Until then I guess just rescue the parse and if it fails re-request?

**Comment by arghgr** [comment] 2018-06-18 18:32
Thanks, will do. Hope you find it!

**Comment by johnbfox** [comment] 2018-06-18 20:59
I saw this issue as well.  Here's a partial snippet of a response:

jQuery11240868049371855212_1529329884001([{"venue":"Nizhny Novgorod","location":"Nizhny Novgorod Stadium","status":"completed","time":"full-time","fifa_id":"300331499","home_team_statistics":{"attempts_on_goal":15,"on_target":5,"off_target":4,"blocked":6,"woodwork":0,"corners":6,"offsides":1,"ball_possession":52,"pass_accuracy":83,"num_passes":421,"passes_completed":351,"distance_covered":102,"balls_recovered":42,"tackles":8,"clearances":29,"yellow_cards":1,"red_cards":0,"fouls_committed":20,"country":"Sweden"},"away_team_statistics":{"attempts_on_goal":5,"on_target":0,"off_target":2,"blocked":3,"woodwork":0,"corners":5,"offsides":0,"ball_possession":48,"pass_accuracy":78,"num_passes":353,"passes_completed":277,"distance_covered":103,"balls_recovered":44,"tackles":12,"clearances":31,"yellow_cards":2,"red_cards":0,"fouls_committed":23,"country":"Korea Republic"},"datetime":"2018-06-18T12:00:00Z","last_event_update_at":"2018-06-18T14:04:12Z","last_score_update_at":"2018-06-18T13:50:50Z","home_team

**Comment by estiens** [comment] 2018-06-18 21:14
I believe this is fixed now (but I still can't reproduce with any regularity, I've only seen it once or twice)

Could any of you in this thread that were seeing it let me know if still seeing it?

**Comment by arghgr** [comment] 2018-06-18 21:28
It's still happening for me. My scraper runs every ten seconds when it's on, I logged the last couple of minutes (looks like my server is on eastern time + 1):
```
now: 2018-06-18 18h 22m 30s
now: 2018-06-18 18h 22m 40s
now: 2018-06-18 18h 22m 50s
now: 2018-06-18 18h 23m 0s
now: 2018-06-18 18h 23m 10s
now: 2018-06-18 18h 23m 20s
now: 2018-06-18 18h 23m 30s
now: 2018-06-18 18h 23m 40s
now: 2018-06-18 18h 23m 50s
now: 2018-06-18 18h 24m 0s
data has jQuery:  jQuery1124014486948935812594_1529352195511
now: 2018-06-18 18h 24m 10s
data has jQuery:  jQuery1124014486948935812594_1529352195511
now: 2018-06-18 18h 24m 20s
now: 2018-06-18 18h 24m 30s
now: 2018-06-18 18h 24m 40s
now: 2018-06-18 18h 24m 50s
data has jQuery:  jQuery1124023891344411480753_1529355277652
now: 2018-06-18 18h 25m 0s
data has jQuery:  jQuery112409258477167193304_1529348057970
now: 2018-06-18 18h 25m 10s
data has jQuery:  jQuery112409258477167193304_1529348057970
now: 2018-06-18 18h 25m 20s
now: 2018-06-18 18h 25m 30s
now: 2018-06-18 18h 25m 40s
now: 2018-06-18 18h 25m 50s
now: 2018-06-18 18h 26m 0s
now: 2018-06-18 18h 26m 10s
now: 2018-06-18 18h 26m 20s
data has jQuery:  jQuery112405187804302733086_1529354630235
now: 2018-06-18 18h 26m 30s
data has jQuery:  jQuery112405187804302733086_1529354630235
now: 2018-06-18 18h 26m 40s
now: 2018-06-18 18h 26m 50s
now: 2018-06-18 18h 27m 0s
now: 2018-06-18 18h 27m 10s
data has jQuery:  jQuery112406418266588236452_1529357018492
now: 2018-06-18 18h 27m 20s
now: 2018-06-18 18h 27m 30s
now: 2018-06-18 18h 27m 40s
now: 2018-06-18 18h 27m 50s
now: 2018-06-18 18h 28m 0s
now: 2018-06-18 18h 28m 10s
now: 2018-06-18 18h 28m 20s
```

**Comment by estiens** [comment] 2018-06-18 22:11
thanks, so weird that it is sporadic. I'll keep looking for an answer

**Comment by estiens** [comment] 2018-06-19 00:03
Another fix for this is in -- it appears RABL doesn't play nice with caching and callbacks, hence the sporadicness -- occasionally someone would cache a JSONP callback and it would get returned for requests without that callback. Now I always return the template and manually do some JSONP stuff if required, but only the template gets cached.

Ran 100 requests and didn't see one that had jQuery but let me know if still an issue

**Comment by arghgr** [comment] 2018-06-19 00:45
It's still happening (ah caching, the bane of web development existence lol). But I added a check for whether the data was wrapped in a function, and stripped out the function and its parentheses accordingly (please see above).

**Comment by estiens** [comment] 2018-06-19 01:03
argghhhh...alright, i'll try again.

**Comment by estiens** [comment] 2018-06-19 02:51
Alright, just did 1000 requests to all matches endpoints and didn't see one come through wrapped in a function either in dev or live, but if anyone still has this problem please comment here.

I can't turn off caching, it's really helped drop the response time, but maybe I can strip out manually somehow.

**Comment by estiens** [comment] 2018-06-19 10:54
Ok, still reports on twitter that this is a thing, I have one more fix in, if that doesn't work I dunno what to do next! except turn off caching but I really don't wanna do that cause it makes me have to triple dyno use...

**Comment by estiens** [comment] 2018-06-19 20:42
This is now fixed once and for all 👯‍♂️ 👯 💃

**Closed by estiens** 2018-06-19 20:42 UTC
